export const typeAcctionBanner= {
  GET_BANNER: "GET_BANNER",
  GET_BANNER_SUCCESS : "GET_BANNER_SUCCESS",
  GET_BANNER_ERROR: "GET_BANNER_ERROR",
  FETCH_REQUESTED : "FETCH_REQUESTED",

  TONG_SUCCESS : "TONG_SUCCESS",
  TRU_SUCCESS : "TRU_SUCCESS",
  TONG_FAILURE : "TONG_FAILURE",
}