export const typeActionTown = {
  GET_USER: "GET_USER",
  SUCCESS_GET_USER: "SUCCESS_GET_USER",
  ERROR_GET_USER: "ERROR_GET_USER",

  SET_USER_TOKEN: "SET_USER_TOKEN",

  CHOOSE_CHARACTER: "CHOOSE_CHARACTER",
  SUCCESS_CHOOSE_CHARACTER: "SUCCESS_CHOOSE_CHARACTER",
  ERROR_CHOOSE_CHARACTER: "ERROR_CHOOSE_CHARACTER",

  SET_ITEMS: "SET_ITEMS",
  SET_HOME: "SET_HOME",
  SET_RANK: "SET_RANK",

  SHOW_DETAIL: "SHOW_DETAIL",
  CLOSE_DETAIL: "CLOSE_DETAIL",

  REPAIR_ITEM: "REPAIR_ITEM",
  SUCCESS_REPAIR_ITEM: "SUCCESS_REPAIR_ITEM",
  ERROR_REPAIR_ITEM: "ERROR_REPAIR_ITEM",

  UPGRADE_ITEM: "UPGRADE_ITEM",
  SUCCESS_UPGRADE_ITEM: "SUCCESS_UPGRADE_ITEM",
  ERROR_UPGRADE_ITEM: "ERROR_UPGRADE_ITEM",

  NOTI_UPGRADE_ITEM: "NOTI_UPGRADE_ITEM",
  UPGRADING: "UPGRADING",

  SHOW_BUY_ITEM: "SHOW_BUY_ITEM",
  CLOSE_SHOW_BUY_ITEM: "CLOSE_SHOW_BUY_ITEM",

  SET_ACTIVITIES: "SET_ACTIVITIES",
  // GET_INFOR_ACTIVITIES: "GET_INFOR_ACTIVITIES",
  // SUCCESS_GET_INFOR_ACTIVITIES: "SUCCESS_GET_INFOR_ACTIVITIES",
  // ERROR_GET_INFOR_ACTIVITIES: "ERROR_GET_INFOR_ACTIVITIES",

  GET_ACTIVITIES: "GET_ACTIVITIES",
  SUCCESS_GET_ACTIVITIES: "SUCCESS_GET_ACTIVITIES",
  ERROR_GET_ACTIVITIES: "ERROR_GET_ACTIVITIES",
  SHOW_TIME_ACTIVITIES: "SHOW_TIME_ACTIVITIES",
  SHOW_REWARD_ACTIVITIES: "SHOW_REWARD_ACTIVITIES",

  GET_REWARD: "GET_REWARD",
  SUCCESS_GET_REWARD: "SUCCESS_GET_REWARD",
  ERROR_GET_REWARD: "ERROR_GET_REWARD",

  CANCEL_ACTIVITIES: "CANCEL_ACTIVITIES",
  SUCCESS_CANCEL_ACTIVITIES: "SUCCESS_CANCEL_ACTIVITIES",
  ERROR_CANCEL_ACTIVITIES: "ERROR_CANCEL_ACTIVITIES",

  STATUS_MODAL_BOX: "STATUS_MODAL_BOX",
  STATUS_POPUP: "STATUS_POPUP",

  BUY_BEAUTY: "BUY_BEAUTY",
  SUCCESS_BUY_BEAUTY: "SUCCESS_BUY_BEAUTY",
  ERROR_BUY_BEAUTY: "ERROR_BUY_BEAUTY",

  BUY_ITEM: "BUY_ITEM",
  SUCCESS_BUY_ITEM: "SUCCESS_BUY_ITEM",
  ERROR_BUY_ITEM: "ERROR_BUY_ITEM",

  STATUS_LOADING: "STATUS_LOADING",

  DELETE_SUCCESS: "DELETE_SUCCESS",

  UPGRADE_BUILDING: "UPGRADE_BUILDING",
  SUCCESS_UPGRADE_BUILDING: "SUCCESS_UPGRADE_BUILDING",
  ERROR_UPGRADE_BUILDING: "ERROR_UPGRADE_BUILDING",

  RECEIVE_INCOME: "RECEIVE_INCOME",

  GET_MATCH: "GET_MATCH",
  SUCCESS_GET_MATCH: "SUCCESS_GET_MATCH",
  ERROR_GET_MATCH: "ERROR_GET_MATCH",

  GET_HISTORY: "GET_HISTORY",
  SUCCESS_GET_HISTORY: "SUCCESS_GET_HISTORY",
  ERROR_GET_HISTORY: "ERROR_GET_HISTORY",

  GET_LEADERBOARD: "GET_LEADERBOARD",
  SUCCESS_GET_LEADERBOARD: "SUCCESS_GET_LEADERBOARD",
  ERROR_GET_LEADERBOARD: "ERROR_GET_LEADERBOARD",

  GET_LEADERBOARD_WALK: "GET_LEADERBOARD_WALK",
  SUCCESS_GET_LEADERBOARD_WALK: "SUCCESS_GET_LEADERBOARD_WALK",
  ERROR_GET_LEADERBOARD_WALK: "ERROR_GET_LEADERBOARD_WALK",

  GET_VERSION: "GET_VERSION",
  SUCCESS_GET_VERSION: "SUCCESS_GET_VERSION",
  ERROR_GET_VERSION: "ERROR_GET_VERSION",
  NOTI_VERSION: "NOTI_VERSION",

  SET_VERSION: "SET_VERSION",
  SUCCESS_SET_VERSION: "SUCCESS_SET_VERSION",
  ERROR_SET_VERSION: "ERROR_SET_VERSION",

  GAME_SOUND: "GAME_SOUND",
  SUCCESS_GAME_SOUND: "SUCCESS_GAME_SOUND",
  ERROR_GAME_SOUND: "ERROR_GAME_SOUND",

  BG_MUSIC: "BG_MUSIC",
  SUCCESS_BG_MUSIC: "SUCCESS_BG_MUSIC",
  ERROR_BG_MUSIC: "ERROR_BG_MUSIC",

  GET_SPIN: "GET_SPIN",
  SUCCESS_GET_SPIN: "SUCCESS_GET_SPIN",
  ERROR_GET_SPIN: "ERROR_GET_SPIN",

  LOCK_ACTION: "LOCK_ACTION",
  UPDATE_PARAMS: "UPDATE_PARAMS",
  HANDLE_SHOW_TIME: "HANDLE_SHOW_TIME",

  SHOW_RANK: "SHOW_RANK",

  SET_BUILDING_LOCAL:"SET_BUILDING_LOCAL",
  SET_ACTIVITY_LOCAL:"SET_ACTIVITY_LOCAL",

  HIDE_ITEM: "HIDE_ITEM",
  SUCCESS_HIDE_ITEM: "SUCCESS_HIDE_ITEM",
  ERROR_HIDE_ITEM: "ERROR_HIDE_ITEM",

  UPGRADE_ABILITY: "UPGRADE_ABILITY",
  SUCCESS_UPGRADE_ABILITY: "SUCCESS_UPGRADE_ABILITY",
  ERROR_UPGRADE_ABILITY: "ERROR_UPGRADE_ABILITY",

  SHOW_RANDOM_BOX_POPUP: "SHOW_RANDOM_BOX_POPUP",
  SHOW_REWARD_RANDOM_BOX_POPUP: "SHOW_REWARD_RANDOM_BOX_POPUP",
  SET_EXPIRED_TOKEN: "SET_EXPIRED_TOKEN",

  CHANGE_LEADERBOARD: "CHANGE_LEADERBOARD",
  SHOW_SCREEN: "SHOW_SCREEN",
  CLOSE_SCREEN: "CLOSE_SCREEN",

  GET_REWARK_WALK: "GET_REWARK_WALK",
  SUCCESS_GET_REWARK_WALK: "SUCCESS_GET_REWARK_WALK",
  ERROR_GET_REWARK_WALK: "ERROR_GET_REWARK_WALK",
  ADS_ENERGY:"ADS_ENERGY",
  ADS_SPIN:"ADS_SPIN",

  GET_COIN_AMOUNT_ACTIVE_WALLET: "GET_COIN_AMOUNT_ACTIVE_WALLET",
  SHOW_WELCOME: "SHOW_WELCOME",
  SHOW_INFOR_SUBSCRISE: "SHOW_INFOR_SUBSCRISE",

  GET_L2 : "GET_L2",
  SUCCESS_GET_L2 : "SUCCESS_GET_L2",
  ERROR_GET_L2 : "ERROR_GET_L2",

  UPDATE_TAU : "UPDATE_TAU",
  SUCCESS_UPDATE_TAU : "SUCCESS_UPDATE_TAU",
  ERROR_UPDATE_TAU : "ERROR_UPDATE_TAU",

  UPDATE_SPIN_ENERGY : "UPDATE_SPIN_ENERGY",
  SUCCESS_UPDATE_SPIN_ENERGY : "SUCCESS_UPDATE_SPIN_ENERGY",
  ERROR_UPDATE_SPIN_ENERGY : "ERROR_UPDATE_SPIN_ENERGY",

  // SUCCESS_UPDATE_ENERGY : "SUCCESS_UPDATE_ENERGY",
  // ERROR_UPDATE_ENERGY : "ERROR_UPDATE_ENERGY",
  
};
